name: Snap Hutao Remastered Alpha
on:
  workflow_dispatch:
  push:
    branches: [ dev ]
    paths-ignore:
      - '.gitattributes'
      - '.github/**'
      - '.gitignore'
      - '.gitmodules'
      - '**.md'
      - 'LICENSE'
      - '**.yml'
  pull_request:
    branches: [ dev ]
    paths-ignore:
      - '.gitattributes'
      - '.github/**'
      - '.gitignore'
      - '.gitmodules'
      - '**.md'
      - 'LICENSE'
      - '**.yml'
      - '**.resx'

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup .NET
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: 10.0

      - name: Cache NuGet packages
        uses: actions/cache@v4
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/Snap.Hutao.Remastered.csproj') }}
          restore-keys: |
            ${{ runner.os }}-nuget-

      - name: Build installer
        id: build
        shell: cmd
        run: Installer\build-installer.cmd
        env:
          CERTIFICATE: ${{ secrets.CERTIFICATE }}
          PW: ${{ secrets.PW }}

      - name: Upload installer
        if: success() && github.event_name != 'pull_request'
        uses: actions/upload-artifact@v5
        with:
          name: Snap.Hutao.Remastered.Alpha-Setup
          path: ${{ github.workspace }}/publish/Snap.Hutao.Remastered-*.exe

      - name: Add summary
        if: success() && github.event_name != 'pull_request'
        shell: pwsh
        run: |
          $summary = "
          > [!WARNING]
          > 该版本是由 CI 程序自动打包生成的 \`Alpha\` 测试版本，包含已经基本完工的新功能及问题修复
          "
          echo $summary >> $Env:GITHUB_STEP_SUMMARY

      - name: Clean up
        shell: pwsh
        run: |
          Write-Host "Cleaning up NuGet cache..."
          Remove-Item -Recurse -Force "$env:USERPROFILE\.nuget\packages"
          Write-Host "NuGet cache cleaned."
